export default {
	'/userposts': ['user'],
	'/userpost': ['user'],
	'/usernewchats': ['user'],
	'/getuserlimits': ['user'],
	'/topics': ['user', 'genie'],
	'/genieposts': ['genie'],
	'/geniechoosepost': ['genie'],
	'/genienewposts': ['genie'],
	'/geniepost': ['genie'],
	'/login': ['all'],
	'/register': ['all'],
	'/forgot_password': ['all'],
	'/reset_password': ['all'],
	'/confirmCodeEmail': ['all'],
};
